export const patternFileExtension = /\.csv+$/i;
export const patternLinesSeparator = /\r\n|\n/;
export const patternRowSeparator = /,(?![^"]*"(?:(?:[^"]*"){2})*[^"]*$)/;
export const patternFullName = /^[a-z]{4,}(?: [a-z]+){0,2}$/i;
export const patternPhone = /^(?:\+1|1)?[0-9]{10}$/;
export const patternLicense = /^[a-z0-9]{6}$/i;
export const patternLicenseStates = /[a-z]{2,}(?:,)?/i;
export const patternFirstDateType = /^\d{1,2}\/\d{1,2}\/\d{4}$/;
export const patternSecondDateType = /^\d{4}-\d{1,2}-\d{1,2}$/;